
CREATE TABLE Account (
	username CHAR(20) PRIMARY KEY,
	password CHAR(32) NOT NULL,
	email CHAR(50) NOT NULL,
	dob DATE NOT NULL,
	displayname CHAR(50),
	bio CHAR(100),
	createTime TIMESTAMP NOT NULL DEFAULT NOW()::TIMESTAMP
);

CREATE TABLE Follow (
	id SERIAL PRIMARY KEY,
	sender CHAR(20) NOT NULL REFERENCES Account(username),
	receiver CHAR(20) NOT NULL REFERENCES Account(username),
	logTime TIMESTAMP NOT NULL DEFAULT NOW()::TIMESTAMP
);

CREATE TABLE Flag (
	id SERIAL PRIMARY KEY,
	label CHAR(20) NOT NULL,
	owner CHAR(20) NOT NULL REFERENCES Account(username)
);

CREATE TABLE Feed (
	id SERIAL PRIMARY KEY,
	actor CHAR(20) NOT NULL REFERENCES Account(username),
	text CHAR(200) NOT NULL,
	fid INT NOT NULL REFERENCES Flag(id),
	postTime TIMESTAMP NOT NULL DEFAULT NOW()::TIMESTAMP 
);

CREATE TYPE Service AS ENUM ('Message', 'Team', 'happy');

CREATE TABLE Billing (
	id SERIAL PRIMARY KEY,
	buyer CHAR(20) NOT NULL REFERENCES Account (username),
	logTime TIMESTAMP NOT NULL DEFAULT NOW()::TIMESTAMP,
);